config/routes.rb
RiccIo::Application.routes.draw do
  resources :links
  match ':in_url' => 'links#go'

end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :out_url, :http_status, :presence => true
  validates :in_url, :uniqueness => true
  validates :out_url, :uniqueness => true
  
  URL_PROTOCOL_HTTP = "http://"
  REGEX_LINK_HAS_PROTOCOL = Regexp.new('^http:\/\/|^https:\/\/', Regexp::IGNORECASE)
  
  def generate_short_url
	charset = ('a'..'z').to_a + ('A'..'Z').to_a + (0..9).to_a 	
	(0...5).map{ charset[rand(charset.size)] }.join
  end

  # ensure the url starts with it protocol and is normalized
  def clean_out_url()
    return nil if self.out_url.blank?
   	self.out_url = URL_PROTOCOL_HTTP + self.out_url.strip unless self.out_url =~ REGEX_LINK_HAS_PROTOCOL
    self.out_url = URI.parse(self.out_url).normalize.to_s
  end
  
  #before_save :clean_out_url
  before_validation :clean_out_url
  
  def create
    count = 0
    begin
      if self.in_url.blank?
      	self.in_url = generate_short_url
      end
      super
    rescue ActiveRecord::RecordNotUnique, ActiveRecord::StatementInvalid => err
      if (count +=1) < 5
        logger.info("retrying with different unique key")
        retry
      else
        logger.info("too many retries, giving up")
        raise
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  http_basic_authenticate_with :name => ENV['RICC_IO_ADMIN_USER'], :password => ENV['RICC_IO_ADMIN_PASSWORD'], :except => :go

  def go
    @link = Link.find_by_in_url!(params[:in_url])
    Link.update_counters @link.id, :hit_count => 1

    redirect_to @link.out_url, :status => @link.http_status
  end

  # GET /links
  # GET /links.json
  def index
    @links = Link.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RiccIo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :in_url %><br />
    <%= f.text_field :in_url %>
  </div>
  <div class="field">
    <%= f.label :out_url %><br />
    <%= f.text_area :out_url %>
  </div>
  <div class="field">
    <%= f.label :http_status %><br />
    <%= f.number_field :http_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
    <th>In url</th>
    <th>Out url</th>
    <th>Http status</th>
    <th>Views</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr>
    <td><%= link.in_url %></td>
    <td><%= link.out_url %></td>
    <td><%= link.http_status %></td>
    <td><%= link.hit_count %></td>
    <td><%= link_to 'Show', link %></td>
    <td><%= link_to 'Edit', edit_link_path(link) %></td>
    <td><%= link_to 'Destroy', link, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>In url:</b>
  <%= @link.in_url %>
</p>

<p>
  <b>Out url:</b>
  <%= @link.out_url %>
</p>

<p>
  <b>Http status:</b>
  <%= @link.http_status %>
</p>

<p>
  <b>View Count:</b>
  <%= @link.hit_count %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>